name: Python Release

on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write
#https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
jobs:
  build:
    name: Build Executables
    runs-on: ${{ matrix.config.os.name }}
    strategy:
      matrix:
        config:
          - os:
              name: macos-14
              filename: macos_arm64
          - os:
              name: windows-latest
              filename: windows_amd64
    steps:
      - name: Checkout source
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'


      - name: Upgrade setuptools, wheel, and install requirements
        run: |
          pip install --upgrade setuptools wheel pyinstaller~=5.13.2 && pip install -r requirements.txt

      - name: Install Playwright browsers (macOS)
        if: matrix.config.os.filename == 'macos_arm64'
        shell: bash
        run: |
          PLAYWRIGHT_BROWSERS_PATH=0 playwright install chromium

      - name: Install Playwright browsers (Windows)
        if: matrix.config.os.filename == 'windows_amd64'
        shell: pwsh
        run: |
          $env:PLAYWRIGHT_BROWSERS_PATH=0
          playwright install chromium

      - name: Copy Playwright browsers to project
        shell: bash
        run: |
          BROWSERS_PATH=$(python -c "import playwright; import os; print(os.path.dirname(playwright.__file__) + '/driver/package/.local-browsers')")
          mkdir -p ms-playwright
          cp -r $BROWSERS_PATH/* ms-playwright/

      - name: Build Pyinstaller
        shell: bash
        run: |
          pyinstaller main.spec
      - name: Zip the Build-windows
        if: matrix.config.os.filename == 'windows_amd64'
        run: Compress-Archive -Path ./dist/MUSE-BiliTickets-Buyer.exe -DestinationPath tmp.zip

      - name: Zip the Build-linux
        if: matrix.config.os.filename != 'windows_amd64'
        run: |
          cd ./dist
          zip -r  ../tmp.zip MUSE-BiliTickets-Buyer

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: tmp.zip
          asset_name: ${{ secrets.ReleaseZipName }}_${{ matrix.config.os.filename }}_${{ github.ref_name }}.zip
          tag: ${{ github.ref }}
          overwrite: true
